services:
  - type: web
    name: zorro-ptt
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PTT_PASSWORD
        sync: false
      - key: NODE_VERSION
        value: 22
      - key: TURN_URL
        sync: false
      - key: TURN_USERNAME
        sync: false
      - key: TURN_CREDENTIAL
        sync: false
